key_id: {{ env['AWS_KMS_KEY'] }}
cipher_texts:
  secret: AQECAHgvsm3WJp0dJXqBkWr+9ODl78mLm+xVX74sayaR4z5yTgAAAGwwagYJKoZIhvcNAQcGoF0wWwIBADBWBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNj1jlE+Y9ccf+867wIBEIApe39HdksUbmU6UpZywfFZ3BBQNjvcbN3qgpt4rr4fjycutK8P9np7Gs8=
secret_files: {}
