key_id: {{ env['AWS_KMS_KEY'] }}
cipher_texts:
  secret: AQECAHiBQgworz68oy/rvQnaemrfJ6SiD7yf9Bn2NZnMaWKyIQAAAGwwagYJKoZIhvcNAQcGoF0wWwIBADBWBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDOFZD/X/yCc8hKGjMQIBEIApM+HALYYo1fKZ1TSSnOq5mZyQzY5pyLYps9A8B5nEuHoDbZ+jy8LaoCg=
secret_files: {}
